{% set version = "0.4.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-htmltools
  version: {{ version|replace("-", "_") }}

source:
  fn: htmltools_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/htmltools_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/htmltools/htmltools_{{ version }}.tar.gz
  sha256: 5b18552e1183b1b90b5cca8e7f95b57e8124c9d517b22aa64783b829513b811a

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base
    - r-rcpp
    - r-digest

  run:
    - r-base
    - r-rcpp
    - r-digest

test:
  commands:
    - $R -e "library('htmltools')"  # [not win]
    - "\"%R%\" -e \"library('htmltools')\""  # [win]

about:
  home: https://github.com/rstudio/htmltools
  license: GPL (>= 2)
  summary: Tools for HTML generation and output.
  license_family: GPL3

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
