{% set version = "0.5.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-htmltools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/htmltools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/htmltools/htmltools_{{ version }}.tar.gz
  sha256: c8b23fab855a89c6ed0f6d6c7cad0ff9c5ae329c0bdb479940443ee752f26659

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-base64enc                # [build_platform != target_platform]
    - r-digest                   # [build_platform != target_platform]
    - r-ellipsis                 # [build_platform != target_platform]
    - r-fastmap                  # [build_platform != target_platform]
    - r-rlang                    # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-base64enc
    - r-digest
    - r-ellipsis
    - r-fastmap >=1.1.0
    - r-rlang >=0.4.10
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-base64enc
    - r-digest
    - r-ellipsis
    - r-fastmap >=1.1.0
    - r-rlang >=0.4.10

test:
  commands:
    - $R -e "library('htmltools')"           # [not win]
    - "\"%R%\" -e \"library('htmltools')\""  # [win]

about:
  home: https://github.com/rstudio/htmltools
  license: GPL-2.0-or-later
  summary: Tools for HTML generation and output.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
